server:
  port: 28083
# no web
# spring.main.web-environment: false
# log config
logging.config: classpath:logback.xml
# xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://192.168.2.2:18083
    # xxl-job, access token
    accessToken: default_token
    # xxl-job executor appname
    executor:
      appname: wzzconnector
      # xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address: ""
      # xxl-job executor server-info
      ip: ""
      port: 19999
      # xxl-job executor log-path
      logpath: /data/applogs/xxl-job/jobhandler
      # xxl-job executor log-retention-days
      logretentiondays: 30

spring:
  influx:
    # 组织： shengqi-tech bucket： eme
    url: http://localhost:8086
    bucket: ems
    org: shengqi
    token: UT9UsuRPsWwdnGqYIYmu9hIejRmpK98bO97hzDnpwfDmJoFrvvVYQloTXoRDCvrbCEcPf-38j6LnaSfrVNzVSg==
  # redis 配置
  redis:
    # 地址
    host: localhost
    #    host: 192.168.2.10
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
customer:
  id: 1

token:
  # 令牌有效期（默认170分钟）
  expireTime: 170

api:
  url: http://192.168.2.2:18083
  findInstance: /instance/findByMap
  findDevice: /device/findByMap
  syncInstance: /instance/sync
  syncDevice: /device/sync
  syncDeviceAlarm: /devicealarm/sync
  login: /sysuser/login
  rtdValue: /monitordata/rtdValue
  workRtdValue: /monitordata/workRtdValue
  username: admin
  password: admin123